---
- hosts: all
  become: yes
  tasks:
    - name: i want to install web server only on REDHAT node
      yum:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"
    - name: i want to start web server  only on REDHAT node
      service:
        name: httpd
        state: started
      when: ansible_os_family=="RedHat"
